language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

branches: # build only on these branches
  only:
    - master

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

notifications:
    email: false
    on_success: change
    on_failure: always

script:
  - go vet ./sdk
  - go vet ./services/...
  - go build ./sdk
  - go build ./services/...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./sdk/...
  - test -z $ACCESS_KEY_ID -a -z $ACCESS_KEY_SECRET || go test -v -timeout 120s ./integration/...

after_success:
  - bash <(curl -s https://codecov.io/bash)
